# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SerialPort.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialPort(object):
    def setupUi(self, SerialPort):
        SerialPort.setObjectName("SerialPort")
        SerialPort.resize(800, 602)
        SerialPort.setMinimumSize(QtCore.QSize(800, 602))
        SerialPort.setMaximumSize(QtCore.QSize(800, 602))
        SerialPort.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(SerialPort)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(180, 10, 611, 391))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 601, 361))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.plotView_1 = PlotWidget(self.tab1)
        self.plotView_1.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_1.setObjectName("plotView_1")
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plotView_2 = PlotWidget(self.tab_2)
        self.plotView_2.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_2.setObjectName("plotView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.plotView_3 = PlotWidget(self.tab_3)
        self.plotView_3.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_3.setObjectName("plotView_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.plotView_4 = PlotWidget(self.tab_4)
        self.plotView_4.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_4.setObjectName("plotView_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.plotView_5 = PlotWidget(self.tab_5)
        self.plotView_5.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_5.setObjectName("plotView_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.plotView_6 = PlotWidget(self.tab_6)
        self.plotView_6.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_6.setObjectName("plotView_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.plotView_7 = PlotWidget(self.tab_7)
        self.plotView_7.setGeometry(QtCore.QRect(10, 10, 571, 311))
        self.plotView_7.setObjectName("plotView_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 409, 781, 141))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 761, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_1 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_1.setObjectName("widget_1")
        self.view_1 = QtWidgets.QLineEdit(self.widget_1)
        self.view_1.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_1.setAlignment(QtCore.Qt.AlignCenter)
        self.view_1.setObjectName("view_1")
        self.label_10 = QtWidgets.QLabel(self.widget_1)
        self.label_10.setGeometry(QtCore.QRect(13, 60, 61, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.widget_1)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.view_2 = QtWidgets.QLineEdit(self.widget_2)
        self.view_2.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_2.setAlignment(QtCore.Qt.AlignCenter)
        self.view_2.setObjectName("view_2")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(13, 60, 61, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.view_3 = QtWidgets.QLineEdit(self.widget_3)
        self.view_3.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_3.setAlignment(QtCore.Qt.AlignCenter)
        self.view_3.setObjectName("view_3")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(13, 60, 61, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_4.setObjectName("widget_4")
        self.view_4 = QtWidgets.QLineEdit(self.widget_4)
        self.view_4.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_4.setAlignment(QtCore.Qt.AlignCenter)
        self.view_4.setObjectName("view_4")
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setGeometry(QtCore.QRect(13, 60, 61, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_5.setObjectName("widget_5")
        self.view_5 = QtWidgets.QLineEdit(self.widget_5)
        self.view_5.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_5.setAlignment(QtCore.Qt.AlignCenter)
        self.view_5.setObjectName("view_5")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setGeometry(QtCore.QRect(13, 60, 71, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.widget_5)
        self.widget_10 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_10.setObjectName("widget_10")
        self.view_6 = QtWidgets.QLineEdit(self.widget_10)
        self.view_6.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_6.setAlignment(QtCore.Qt.AlignCenter)
        self.view_6.setObjectName("view_6")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setGeometry(QtCore.QRect(13, 60, 61, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.widget_10)
        self.widget_7 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_7.setObjectName("widget_7")
        self.view_7 = QtWidgets.QLineEdit(self.widget_7)
        self.view_7.setGeometry(QtCore.QRect(10, 9, 71, 41))
        self.view_7.setAlignment(QtCore.Qt.AlignCenter)
        self.view_7.setReadOnly(False)
        self.view_7.setObjectName("view_7")
        self.label_13 = QtWidgets.QLabel(self.widget_7)
        self.label_13.setGeometry(QtCore.QRect(13, 60, 61, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.widget_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(9, 10, 161, 391))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 368))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSerial = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.labelSerial.setFont(font)
        self.labelSerial.setObjectName("labelSerial")
        self.gridLayout.addWidget(self.labelSerial, 2, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.closeButton.setFont(font)
        self.closeButton.setIconSize(QtCore.QSize(20, 40))
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 160, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 2)
        self.labelBaud = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.labelBaud.setFont(font)
        self.labelBaud.setObjectName("labelBaud")
        self.gridLayout.addWidget(self.labelBaud, 3, 0, 1, 1)
        self.Button_quit = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.Button_quit.setFont(font)
        self.Button_quit.setObjectName("Button_quit")
        self.gridLayout.addWidget(self.Button_quit, 8, 0, 1, 2)
        self.serialSetLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.serialSetLabel.setFont(font)
        self.serialSetLabel.setObjectName("serialSetLabel")
        self.gridLayout.addWidget(self.serialSetLabel, 4, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 5, 0, 1, 1)
        self.baudComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.baudComboBox.setFont(font)
        self.baudComboBox.setCurrentText("1200")
        self.baudComboBox.setIconSize(QtCore.QSize(30, 20))
        self.baudComboBox.setObjectName("baudComboBox")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.baudComboBox.addItem("")
        self.gridLayout.addWidget(self.baudComboBox, 3, 1, 1, 1)
        self.serialComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.serialComboBox.setFont(font)
        self.serialComboBox.setIconSize(QtCore.QSize(30, 20))
        self.serialComboBox.setObjectName("serialComboBox")
        self.gridLayout.addWidget(self.serialComboBox, 2, 1, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.openButton.setFont(font)
        self.openButton.setIconSize(QtCore.QSize(20, 40))
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 4, 1, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 1, 0, 1, 2)
        SerialPort.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SerialPort)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        SerialPort.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SerialPort)
        self.statusbar.setObjectName("statusbar")
        SerialPort.setStatusBar(self.statusbar)

        self.retranslateUi(SerialPort)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(SerialPort)

    def retranslateUi(self, SerialPort):
        _translate = QtCore.QCoreApplication.translate
        SerialPort.setWindowTitle(_translate("SerialPort", "SerialPort"))
        self.groupBox.setTitle(_translate("SerialPort", "波形显示区域"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("SerialPort", "流量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SerialPort", "温度"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SerialPort", "动脉压"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SerialPort", "静脉压"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("SerialPort", "透析液压力"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("SerialPort", "电导"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("SerialPort", "PH"))
        self.groupBox_2.setTitle(_translate("SerialPort", "数值显示区域"))
        self.label_10.setText(_translate("SerialPort", "流量"))
        self.label_6.setText(_translate("SerialPort", "温度"))
        self.label_7.setText(_translate("SerialPort", "动脉压"))
        self.label_15.setText(_translate("SerialPort", "静脉压"))
        self.label_11.setText(_translate("SerialPort", "透析液压力"))
        self.label_14.setText(_translate("SerialPort", "电导"))
        self.label_13.setText(_translate("SerialPort", "PH"))
        self.groupBox_3.setTitle(_translate("SerialPort", "串口设置"))
        self.labelSerial.setText(_translate("SerialPort", "串口选择"))
        self.closeButton.setText(_translate("SerialPort", "关闭"))
        self.labelBaud.setText(_translate("SerialPort", "波特率"))
        self.Button_quit.setText(_translate("SerialPort", "退出"))
        self.serialSetLabel.setText(_translate("SerialPort", "串口操作"))
        self.baudComboBox.setItemText(0, _translate("SerialPort", "1200"))
        self.baudComboBox.setItemText(1, _translate("SerialPort", "2400"))
        self.baudComboBox.setItemText(2, _translate("SerialPort", "4800"))
        self.baudComboBox.setItemText(3, _translate("SerialPort", "9600"))
        self.baudComboBox.setItemText(4, _translate("SerialPort", "14400"))
        self.baudComboBox.setItemText(5, _translate("SerialPort", "19200"))
        self.baudComboBox.setItemText(6, _translate("SerialPort", "38400"))
        self.baudComboBox.setItemText(7, _translate("SerialPort", "43000"))
        self.baudComboBox.setItemText(8, _translate("SerialPort", "57600"))
        self.baudComboBox.setItemText(9, _translate("SerialPort", "76800"))
        self.baudComboBox.setItemText(10, _translate("SerialPort", "115200"))
        self.baudComboBox.setItemText(11, _translate("SerialPort", "128000"))
        self.baudComboBox.setItemText(12, _translate("SerialPort", "230400"))
        self.baudComboBox.setItemText(13, _translate("SerialPort", "256000"))
        self.baudComboBox.setItemText(14, _translate("SerialPort", "460800"))
        self.baudComboBox.setItemText(15, _translate("SerialPort", "921600"))
        self.baudComboBox.setItemText(16, _translate("SerialPort", "1382400"))
        self.openButton.setText(_translate("SerialPort", "打开"))
        self.refreshButton.setText(_translate("SerialPort", "刷新"))
from pyqtgraph import PlotWidget
